### DISCUSSION TITLE
Where are cloudflare pages environment variables attached?

### DISCUSSION THREAD

**Discussion by targetlucked69** [TanStack/router#2985] [General]
I have a file and when I log `process.env.MY_KEY` or `import.meta.env.MY_KEY`, it is undefined. I'm calling it inside a page like this:

```ts
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_hello')({
  beforeLoad: ({ context }) => {
    console.log(process.env.MY_KEY);
    console.log(import.meta.env.MY_KEY);
  },
})
```

and here's my `wrangler.toml` file

```toml
name = "tanstack-start-example"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-25"

[vars]
MY_KEY = "some-test-string"
```

and my `app.config.ts`

```ts
import { defineConfig } from '@tanstack/start/config'
import { cloudflare } from 'unenv'

export default defineConfig({
  server: {
    preset: "cloudflare-pages",
    unenv: cloudflare,
  },
});
```

This works with other deployments btw, just wrangler and deployment to CF pages. 

How do I get access to env variables?
