### DISCUSSION TITLE
Docker compose with tanstack start

### DISCUSSION THREAD

**Discussion by thibaultdenis014** [TanStack/router#3147] [Q&A]
Hey guys,

I am struggling to get  docker working with tanstack start in DEV mode ? I keep getting this error. I have tried to play around with the host name but with no luck: 
![image](https://github.com/user-attachments/assets/d1783ff8-f718-4939-aac3-630920452515)

Reproduction steps:
- follow the build from scratch guide from the docs [here](https://tanstack.com/router/latest/docs/framework/react/start/build-from-scratch)
- copy the dev.Dockerfile and docker-compose below.
- run `docker compose up`

Here is what my dev.Dockerfile looks like:
```Dockerfile
FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN corepack enable pnpm && pnpm i

COPY . .

CMD ["pnpm", "dev"]
```

And my docker-compose file:
```yaml
services:
  server:
    container_name: my_container
    build:
      context: ./
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
```

**Comment by jaredjj3** [comment]
I have the same problem. HMR does not work in Docker, but it works outside of it.

It seems that vinxi doesn't allow you to configure the underlying [vite hmr options](https://vite.dev/config/server-options#server-hmr) needed to get this to work in Docker. I suspect I need to set `vite.server.hmr.host` to `'0.0.0.0'` and/or `vite.server.hmr.port` to a static port that's mapped in the Docker compose file. https://github.com/nksaraf/vinxi/issues/394 is an FR to allow HMR ports to be configurable.

>I have tried to play around with the host name but with no luck

How are you changing the host name? I couldn't figure out how to configure this.

**Reply by timothyaveni** [reply]
I was able to configure this with

app.config.ts
```ts
export default defineConfig({
  ..
  routers: {
    client: {
      vite: {
        server: { // gives a ts error, but still seems to work
          hmr: {
            port: 3124
          }
        }
      }
    }
  },
  ...
})
```

**Comment by thibaultdenis014** [comment]
I tried to set it in the docker compose like so with no luck:

```yaml
.....
  server:
    container_name: gym_graphs_server
    hostname: 0.0.0.0
.....
```
