### ISSUE TITLE
Vite dev server crashes if router plugin is imported before vite plugin

### ISSUE THREAD

**Issue by emanuele-toma** [TanStack/router#2972]
### Which project does this relate to?

Router

### Describe the bug

Using starter project **with bun**, in file `/vite.config.ts`
```ts
// If router plugin is imported before vite plugin, dev server crashes
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
```

Dev server error
```bash
failed to load config from /app/vite.config.ts
error when starting dev server:
undefined
```

This error can be easily reproduced using bun docker image:
```yaml
services:
  frontend:
    image: oven/bun:latest # == oven/bun:1.1.38-debian
    user: 1000:1000
    ports: 
      - 5173:5173
    volumes:
      - ./:/app
    working_dir: app
    command: sh -c "bun i && bun dev --host"
```

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-hcnpenqu?file=vite.config.ts&view=editor

### Steps to Reproduce the Bug or Issue

1. Install starter project with bun `bun create @tanstack/router`
2. In file `vite.config.ts` put `@tanstack/router-plugin/vite` import **before** `@vitejs/plugin-react`
3. Run vite dev server with `oven/bun:latest` docker image

### Expected behavior

This is not documented behaviour.
A notice that warns user to **not** put router plugin before vite plugin would be useful, maybe in [Quick Start](https://github.com/TanStack/router/blob/main/docs/framework/react/quick-start.md)

For example
```ts
// vite.config.ts
import { defineConfig } from 'vite'
import viteReact from '@vitejs/plugin-react'

// this import should always be after @vitejs/plugin-react
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    TanStackRouterVite(),
    viteReact(),
    // ...,
  ],
})
```

### Platform

- OS: Debian
- Bun: 1.1.38
- Router: ^1.87.2
- Plugin ^1.86.0 

### Additional context

This happened because I have a prettier plugin that automatically sorts imports, it took me a while to realize what went wrong.
Also I can reproduce this issue only using the provided docker image, if I use bun on the host machine I can't reproduce it.
