### ISSUE TITLE
Unknown path aliases in docker container

### ISSUE THREAD

**Issue by nguyenthinhkha** [TanStack/router#3950]
### Which project does this relate to?

Start

### Describe the bug

Unknown path aliases in docker container
Refer to path aliases set up: https://tanstack.com/start/latest/docs/framework/react/path-aliases

### Your Example Website or App

https://codesandbox.io/p/devbox/github/tanstack/router/tree/main/examples/react/start-basic-auth

### Steps to Reproduce the Bug or Issue

1. Use basic auth example
2. Add docker file, like this
```
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npm run db:gen

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
``` 
3. add docker compose for db & app
```
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5001:5432"
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    volumes:
      - ./:/app
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npx prisma generate --sql &&  npm run dev"

volumes:
  db_data:
    driver: local

```
4. run `docker compose up` to start 2 services
5. Go to `http://{your-ip}:3000/login`

You will see the errors on terminal like this
```
Error in renderToPipeableStream: Error: Cannot find module '@/components/login' imported from '/app/src/routes/(auth)/login.tsx'
```
while it's working fine if you run `npm run dev` without docker

### Expected behavior

We can launch app in docker container

### Platform

- OS: Linux
- Browser: Chrome
- Version: latest

### Additional context

Tanstack start use Vinxi, so I think the problem can be related to that lib - https://vinxi.vercel.app/guide/aliases.html
